apiVersion: v1
kind: Service
metadata:
  name: jenkins-test-app-service
spec:
  type: LoadBalancer
  selector:
    app: jenkins-test-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080